baseURL = 'https://care.ctrl-alt-gg.hu/'
languageCode = 'en-us'
title = 'Ctrl-Alt-GG Care'
theme = 'pehtheme-hugo'

summaryLength = '20' # <- 20 words are approximately 160 characters
#googleAnalytics = 'G-MEASUREMENT_ID' # <- Your GA-4
#disqusShortname = 'your-disqus-shortname' # <- Get form here : https://disqus.com

[params]
	# Meta description, not exceeding 160 characters, used for the meta description within the HTML head
	description = "Technical support, network troubleshooting, and help for the Ctrl-Alt-GG LAN community."
	mainSections = 'posts'

[author]
	name = 'Ctrl-Alt-GG'
	bio = 'Practical support for gaming, logistics, and community wellbeing.'
	avatar = '/favicon.svg'
#	twitter = 'https://twitter.com/insertapps'

[pagination]
	pagerSize = 6 # <- Set the desired number of posts per page 

[menu] # Menu management
	[[menu.main]]
		name = 'Home'
		pageRef = '/'
		weight = 10
	[[menu.main]]
		name = 'Network'
		pageRef = '/categories/network'
		weight = 15
	[[menu.main]]
		name = 'Hardware'
		pageRef = '/categories/hardware'
		weight = 16
	[[menu.main]]
		name = 'Software'
		pageRef = '/categories/software'
		weight = 17
	[[menu.main]]
		name = 'Wellness'
		pageRef = '/categories/wellness'
		weight = 18
	[[menu.main]]
		name = 'Get Help'
		pageRef = '/categories/help'
		weight = 19

[module]
  [module.hugoVersion]
    extended = false
    min = "0.116.0"
  [module.mounts] # Directing the static folder to assets.
	source = 'assets'
	target = 'static'
